# Generated by Django 4.0 on 2021-12-20 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='itemm',
        ),
    ]
