# Generated by Django 4.0 on 2021-12-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_item_itemm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='itemm',
            new_name='item_model',
        ),
    ]
